# Generated by Django 4.2.26 on 2025-11-24 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Sample ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Sample Name")),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("IPSC", "Induced Pluripotent Stem Cell"),
                            ("ESC", "Embryonic Stem Cell"),
                            ("MSC", "Mesenchymal Stem Cell"),
                            ("HSC", "Hematopoietic Stem Cell"),
                            ("NSC", "Neural Stem Cell"),
                            ("OTHER", "Other"),
                        ],
                        default="IPSC",
                        max_length=10,
                        verbose_name="Sample Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=200, verbose_name="Source"),
                ),
                (
                    "donor_info",
                    models.TextField(blank=True, verbose_name="Donor Information"),
                ),
                (
                    "storage_location",
                    models.CharField(max_length=200, verbose_name="Storage Location"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("DEPLETED", "Depleted"),
                            ("RESERVED", "Reserved"),
                            ("QUARANTINE", "Quarantine"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(default=0.0, verbose_name="Quantity (vials)"),
                ),
                (
                    "passage_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Passage Number"
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Collection Date"
                    ),
                ),
                (
                    "storage_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Storage Date"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration Date"
                    ),
                ),
                (
                    "viability",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Viability (%)"
                    ),
                ),
                (
                    "quality_control_notes",
                    models.TextField(blank=True, verbose_name="Quality Control Notes"),
                ),
                (
                    "research_use_only",
                    models.BooleanField(default=True, verbose_name="Research Use Only"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sample_images/",
                        verbose_name="Sample Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_samples",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
                "ordering": ["-created_at"],
            },
        ),
    ]
