# Generated by Django 4.2.26 on 2025-12-15 07:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSample",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Sample ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Sample Name")),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("IPSC", "Induced Pluripotent Stem Cell"),
                            ("ESC", "Embryonic Stem Cell"),
                            ("MSC", "Mesenchymal Stem Cell"),
                            ("HSC", "Hematopoietic Stem Cell"),
                            ("NSC", "Neural Stem Cell"),
                            ("OTHER", "Other"),
                        ],
                        default="IPSC",
                        max_length=10,
                        verbose_name="Sample Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=200, verbose_name="Source"),
                ),
                (
                    "donor_info",
                    models.TextField(blank=True, verbose_name="Donor Information"),
                ),
                (
                    "storage_location",
                    models.CharField(max_length=200, verbose_name="Storage Location"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("DEPLETED", "Depleted"),
                            ("RESERVED", "Reserved"),
                            ("QUARANTINE", "Quarantine"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantity (vials)",
                    ),
                ),
                (
                    "passage_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Passage Number",
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Collection Date"
                    ),
                ),
                (
                    "storage_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Storage Date"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration Date"
                    ),
                ),
                (
                    "viability",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Viability (%)",
                    ),
                ),
                (
                    "quality_control_notes",
                    models.TextField(blank=True, verbose_name="Quality Control Notes"),
                ),
                (
                    "research_use_only",
                    models.BooleanField(default=True, verbose_name="Research Use Only"),
                ),
                (
                    "image",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sample Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sample",
                "verbose_name_plural": "historical Samples",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="Site Logo",
                    ),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        default="Inventory Management System of Hong Kong Cell and Stem Cell Resource Center",
                        max_length=200,
                        verbose_name="Site Name (English)",
                    ),
                ),
                (
                    "site_name_zh_hant",
                    models.CharField(
                        default="香港細胞及幹細胞資源中心庫存管理系統",
                        max_length=200,
                        verbose_name="Site Name (Traditional Chinese)",
                    ),
                ),
                (
                    "site_name_zh_hans",
                    models.CharField(
                        default="香港细胞及干细胞资源中心库存管理系统",
                        max_length=200,
                        verbose_name="Site Name (Simplified Chinese)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AlterField(
            model_name="sample",
            name="passage_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Passage Number",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="quantity",
            field=models.FloatField(
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity (vials)",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="viability",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Viability (%)",
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["sample_id"], name="samples_sam_sample__75a926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["status"], name="samples_sam_status_431764_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["sample_type"], name="samples_sam_sample__029233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["-updated_at"], name="samples_sam_updated_1a98ca_idx"
            ),
        ),
        migrations.AddField(
            model_name="historicalsample",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="historicalsample",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
